name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nim Setup
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 'stable'

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Install Dependencies
        run: |
          nimble install zigcc nigui -y
          Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.nimble\bin"

      - name: Compile GUI
        run: nim c -d:zigwin src/gui.nim

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DAOTools-Windows
          path: DAOTools.exe
